### PR TITLE
Add .NET Standard 2.0 as target framework.

### PR DESCRIPTION
**Pull request by H1Gdev**
Please do not remove `.NET Standard` from target frameworks yet.

### CODE REVIEW

**Comment by TylerBrinks** [comment]
This has been merged for the time being.  However, going forward towards .NET 6 the plan is to drop support for the legacy standard disposition in order to mirror the unified .NET 5/6 framework.

https://devblogs.microsoft.com/dotnet/the-future-of-net-standard/

**Comment by H1Gdev** [comment]
@TylerBrinks 

Thanks !!
When do you plan to release to NuGet ?

**Comment by TylerBrinks** [comment]
Today, actually.

**Comment by H1Gdev** [comment]
@TylerBrinks 
I downloaded 4.1.2 with NuGet and it didn't have .Net Standard 2.0.
https://www.nuget.org/packages/excss/#dependencies-tab

Would you please check package ?

**Comment by TylerBrinks** [comment]
You're right - for some reason the package step didn't produce a net 2.0 output.  I'll rev the version and re-submit the package.

**Comment by TylerBrinks** [comment]
Submitted.  The update will be available as soon as NuGet.org indexes the update.

**Comment by H1Gdev** [comment]
@TylerBrinks 
Thank you so much !!

**Pull request merged**
